# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\91498\Documents\code\opengl_l

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\91498\Documents\code\opengl_l

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\91498\Documents\code\opengl_l\CMakeFiles C:\Users\91498\Documents\code\opengl_l\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\91498\Documents\code\opengl_l\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/build
.PHONY : main/fast

KiIndexBuffer.obj: KiIndexBuffer.cpp.obj

.PHONY : KiIndexBuffer.obj

# target to build an object file
KiIndexBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiIndexBuffer.cpp.obj
.PHONY : KiIndexBuffer.cpp.obj

KiIndexBuffer.i: KiIndexBuffer.cpp.i

.PHONY : KiIndexBuffer.i

# target to preprocess a source file
KiIndexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiIndexBuffer.cpp.i
.PHONY : KiIndexBuffer.cpp.i

KiIndexBuffer.s: KiIndexBuffer.cpp.s

.PHONY : KiIndexBuffer.s

# target to generate assembly for a file
KiIndexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiIndexBuffer.cpp.s
.PHONY : KiIndexBuffer.cpp.s

KiLogger.obj: KiLogger.cpp.obj

.PHONY : KiLogger.obj

# target to build an object file
KiLogger.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiLogger.cpp.obj
.PHONY : KiLogger.cpp.obj

KiLogger.i: KiLogger.cpp.i

.PHONY : KiLogger.i

# target to preprocess a source file
KiLogger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiLogger.cpp.i
.PHONY : KiLogger.cpp.i

KiLogger.s: KiLogger.cpp.s

.PHONY : KiLogger.s

# target to generate assembly for a file
KiLogger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiLogger.cpp.s
.PHONY : KiLogger.cpp.s

KiShader.obj: KiShader.cpp.obj

.PHONY : KiShader.obj

# target to build an object file
KiShader.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiShader.cpp.obj
.PHONY : KiShader.cpp.obj

KiShader.i: KiShader.cpp.i

.PHONY : KiShader.i

# target to preprocess a source file
KiShader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiShader.cpp.i
.PHONY : KiShader.cpp.i

KiShader.s: KiShader.cpp.s

.PHONY : KiShader.s

# target to generate assembly for a file
KiShader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiShader.cpp.s
.PHONY : KiShader.cpp.s

KiVertexArray.obj: KiVertexArray.cpp.obj

.PHONY : KiVertexArray.obj

# target to build an object file
KiVertexArray.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexArray.cpp.obj
.PHONY : KiVertexArray.cpp.obj

KiVertexArray.i: KiVertexArray.cpp.i

.PHONY : KiVertexArray.i

# target to preprocess a source file
KiVertexArray.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexArray.cpp.i
.PHONY : KiVertexArray.cpp.i

KiVertexArray.s: KiVertexArray.cpp.s

.PHONY : KiVertexArray.s

# target to generate assembly for a file
KiVertexArray.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexArray.cpp.s
.PHONY : KiVertexArray.cpp.s

KiVertexBuffer.obj: KiVertexBuffer.cpp.obj

.PHONY : KiVertexBuffer.obj

# target to build an object file
KiVertexBuffer.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexBuffer.cpp.obj
.PHONY : KiVertexBuffer.cpp.obj

KiVertexBuffer.i: KiVertexBuffer.cpp.i

.PHONY : KiVertexBuffer.i

# target to preprocess a source file
KiVertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexBuffer.cpp.i
.PHONY : KiVertexBuffer.cpp.i

KiVertexBuffer.s: KiVertexBuffer.cpp.s

.PHONY : KiVertexBuffer.s

# target to generate assembly for a file
KiVertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexBuffer.cpp.s
.PHONY : KiVertexBuffer.cpp.s

KiVertexBufferLayout.obj: KiVertexBufferLayout.cpp.obj

.PHONY : KiVertexBufferLayout.obj

# target to build an object file
KiVertexBufferLayout.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexBufferLayout.cpp.obj
.PHONY : KiVertexBufferLayout.cpp.obj

KiVertexBufferLayout.i: KiVertexBufferLayout.cpp.i

.PHONY : KiVertexBufferLayout.i

# target to preprocess a source file
KiVertexBufferLayout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexBufferLayout.cpp.i
.PHONY : KiVertexBufferLayout.cpp.i

KiVertexBufferLayout.s: KiVertexBufferLayout.cpp.s

.PHONY : KiVertexBufferLayout.s

# target to generate assembly for a file
KiVertexBufferLayout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/KiVertexBufferLayout.cpp.s
.PHONY : KiVertexBufferLayout.cpp.s

main.obj: main.cpp.obj

.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\main.dir\build.make CMakeFiles/main.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... main
	@echo ... KiIndexBuffer.obj
	@echo ... KiIndexBuffer.i
	@echo ... KiIndexBuffer.s
	@echo ... KiLogger.obj
	@echo ... KiLogger.i
	@echo ... KiLogger.s
	@echo ... KiShader.obj
	@echo ... KiShader.i
	@echo ... KiShader.s
	@echo ... KiVertexArray.obj
	@echo ... KiVertexArray.i
	@echo ... KiVertexArray.s
	@echo ... KiVertexBuffer.obj
	@echo ... KiVertexBuffer.i
	@echo ... KiVertexBuffer.s
	@echo ... KiVertexBufferLayout.obj
	@echo ... KiVertexBufferLayout.i
	@echo ... KiVertexBufferLayout.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

